include:
  - docker-compose.yml

services:
  ollama:
    image: ollama/ollama:latest
    environment:
      - MODEL_NAME:"llama3:8b-instruct-q4_0"
      - OLLAMA_KEEP_ALIVE=24h
    ports:
        - 11434:11434
    volumes:
        - ollamadata:/root/.ollama
        - ./scripts/ollama/entrypoint.sh:/entrypoint.sh
    hostname: ollama
    pull_policy: always
    tty: true
    restart: always
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]

volumes:
    ollamadata: