apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-chatbot-framework.fullname" . }}
  labels:
    app: "ai-chatbot-framework"
    name: "ai-chatbot-framework-web"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "ai-chatbot-framework"
      name: "ai-chatbot-framework-web"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      {{- end }}
      labels:
        app: "ai-chatbot-framework"
        name: "ai-chatbot-framework-web"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ai-chatbot-framework"]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
