---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-chatbot-framework.fullname" . }}-backend
  labels:
    app: "ai-chatbot-framework"
    name: "ai-chatbot-framework-backend"
    {{- include "ai-chatbot-framework.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http-backend
  selector:
    name: "ai-chatbot-framework-backend"

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-chatbot-framework.fullname" . }}-frontend
  labels:
    app: "ai-chatbot-framework"
    name: "ai-chatbot-framework-frontend"
    {{- include "ai-chatbot-framework.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http-frontend
  selector:
    name: "ai-chatbot-framework-frontend"