name: Evaluate Backend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.0.0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.x'
          architecture: 'x64'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff

      - name: Run Ruff
        run: ruff check --output-format=github .
        
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest