name: Evaluate Frontend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - 'frontend/**'
  
jobs:     
  test-nextjs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.0.0
      
      - name: build nextjs app
        run: |
          docker build -t ai-chatbot-framework_frontend:dev -f frontend/Dockerfile frontend/
